### ISSUE TITLE
Getting issue when extracting ktsl2stbin

### ISSUE THREAD

**Issue by Enspiron** [Hairo/kvs-tools#1]
Hello, when I run the program, I get this error. 
```Reading file...
0 files
Traceback (most recent call last):
  File "D:\Datamining\section1\nx\sound\kvs_extract.py", line 51, in <module>
    write_file(os.path.join("out", str(size-1)+".kvs"), files_start[-1], last_offset)
IndexError: list index out of range```

How could this be fixed?

**Comment by Hairo** [comment]
it says 0 files, are you using a .ktsl2stbin file? (not to mention that i haven't touched this in a while, some stuff might have changed in the Final Battle update).

**Comment by Tha14** [comment]
Hey, I am also trying to use this script with a series of files that have the KOVS header striped or replaced. I assume it's the same series of files as the ones that @Enspiron is trying to extract. 

EDIT: Found KVs, KvS and kVS headers inside the .ktsl2stbin and extract those to kvs but they are incorrect.

**Comment by Hairo** [comment]
if you mean the files with a KTSS header, they are different from the regular KOVS files, [kvs2ogg](http://dl.deiyu-studio.net/kvs2ogg/) doesn't work on them either, if you want to extract them just replace `KOVS` with `KTSS` (at line 40) or whatever different header they have.

**Comment by Tha14** [comment]
> 
> 
> if you mean the files with a KTSS header, they are different from the regular KOVS files, [kvs2ogg](http://dl.deiyu-studio.net/kvs2ogg/) doesn't work on them either, if you want to extract them just replace `KOVS` with `KTSS` (at like 40) or whatever different header they have.

Thanks, will try that now :)

**Comment by Tha14** [comment]
@Hairo Yep, they were KTSS all along. Thanks a bunch :)

**Comment by Hairo** [comment]
Ok, script now extracts both KOVS and KTSS files.
